// Generated by CoffeeScript 1.7.1
(function() {
  var _listenerIIFE;

  (_listenerIIFE = function(OJ) {

    /*
    Define the subscriber methods which are available to this class.
     */
    var panelSubscribers, panellisteners;
    panelSubscribers = OJ.object();
    panelSubscribers.afterlayout = "afterlayout";
    OJ.constant(OJ.panels, "subscribers", panelSubscribers);

    /*
    Create a new subscribers collection. This returns a subscribers object with an add method.
     */
    OJ.panels.subscribers.register("subscribers", panellisteners = function() {
      "use strict";
      var ret;
      ret = OJ.makeSubscribers("panelSubscribers", "panels");
      return ret;
    });
  })((typeof global !== "undefined" && global ? global : (typeof window !== "undefined" ? window : this)).OJ);

}).call(this);

//# sourceMappingURL=_panelSubscribers.map
