// Generated by CoffeeScript 1.7.1
(function() {
  (function(OJ) {

    /*
    Create an HTML Element through ThinDom
     */
    var component;
    component = function(tag, owner, opt) {
      var ret;
      if (!tag.startsWith('x-')) {
        tag = 'x-' + tag;
      }
      ret = OJ.element(tag, opt.props, opt.styles);
      return OJ.nodeFactory(ret, owner);
    };
    OJ.register('component', component);
  })((typeof global !== 'undefined' && global ? global : (typeof window !== 'undefined' ? window : this)).OJ);

}).call(this);

//# sourceMappingURL=component.map
