// Generated by CoffeeScript 1.7.1
(function() {
  (function(OJ) {
    var className, nodeName;
    nodeName = 'x-easypie';
    className = 'easypie';
    OJ.components.members[nodeName] = className;
    OJ.components.register(className, function(options, owner) {
      var cmpnt, defaults, ret;
      defaults = {
        config: {
          barColor: '#efefef',
          percent: '50',
          size: '95',
          lineWidth: '',
          trackColor: '#efefef',
          scaleColor: 'false'
        },
        data: [],
        props: {
          "class": 'chart easy-pie inline-block primary'
        }
      };
      OJ.extend(defaults, options);
      ret = OJ.component(defaults, owner, nodeName);
      defaults.props['data-percent'] = defaults.config.percent;
      cmpnt = ret.div(defaults);
      cmpnt.$.easyPieChart(defaults.config);
      return ret;
    });
  })((typeof global !== 'undefined' && global ? global : (typeof window !== 'undefined' ? window : this)).OJ);

}).call(this);

//# sourceMappingURL=easypie.map
