// Generated by CoffeeScript 1.7.1
(function() {
  (function(OJ) {
    var className, nodeName;
    nodeName = 'x-input-group';
    className = 'inputgroup';
    OJ.components.members[nodeName] = className;
    OJ.components.register(className, function(options, owner) {
      var cmpnt, defaults, forId, ret;
      forId = OJ.createUUID();
      defaults = {
        props: {
          "class": 'form-group'
        },
        events: {
          change: _.noop
        },
        "for": forId,
        labelText: '',
        inputOpts: {
          props: {
            id: forId,
            type: 'text',
            "class": '',
            placeholder: '',
            value: ''
          }
        }
      };
      OJ.extend(defaults, options, true);
      ret = OJ.component(defaults, owner, nodeName);
      cmpnt = ret.div({
        props: {
          "class": 'form-group'
        }
      });
      ret.groupLabel = cmpnt.label({
        props: {
          "for": forId
        },
        text: defaults.labelText
      });
      defaults.inputOpts.props["class"] += ' form-control';
      ret.groupInput = cmpnt.input(defaults.inputOpts);
      ret.groupValue = function() {
        return ret.groupInput.val();
      };
      return ret;
    });
  })((typeof global !== 'undefined' && global ? global : (typeof window !== 'undefined' ? window : this)).OJ);

}).call(this);

//# sourceMappingURL=inputgroup.js.map