// Generated by CoffeeScript 1.7.1
(function() {
  (function(OJ) {
    OJ.components.members.push('subnav');
    OJ.components.register('subnav', function(owner, props) {
      var defaults, ret, ul;
      defaults = {
        active: '',
        menu: [
          {
            name: '',
            href: ''
          }
        ]
      };
      OJ.extend(defaults, props);
      ret = OJ.component(owner, 'sidebar-subnav');
      ul = ret.ul({
        attr: {
          "class": 'active'
        }
      });
      OJ.each(defaults.menu, function(val, key) {
        var li;
        if (val.name === defaults.active) {
          li = ul.li({
            attr: {
              "class": 'active'
            }
          });
        } else {
          li = ul.li();
        }
        li.a({
          attr: val
        });
      });
      return ret;
    });
  })((typeof global !== 'undefined' && global ? global : (typeof window !== 'undefined' ? window : this)).OJ);

}).call(this);

//# sourceMappingURL=subnav.map
