// Generated by CoffeeScript 1.7.1
(function() {
  (function(OJ) {
    var className, nodeName;
    nodeName = 'x-tabs';
    className = 'tabs';
    OJ.components.members[className] = nodeName;
    OJ.components.register(className, function(options, owner) {
      var content, defaults, first, ret, tabs;
      defaults = {
        tabs: {},
        props: {
          "class": ''
        }
      };
      OJ.extend(defaults, options, true);
      ret = OJ.component(defaults, owner, nodeName);
      tabs = ret.make('ul', {
        props: {
          "class": 'nav nav-tabs'
        }
      });
      content = ret.make('div', {
        props: {
          "class": 'tab-content'
        }
      });
      first = true;
      OJ.each(defaults.tabs, function(tabVal, tabName) {
        var a, tabClass, tabContentClass;
        tabClass = '';
        if (first) {
          first = false;
          tabClass = 'active';
        }
        a = tabs.make('li', {
          props: {
            "class": tabClass
          }
        }).make('a', {
          text: tabName,
          props: {
            href: '#' + tabName,
            'data-toggle': 'tab'
          },
          events: {
            click: function() {
              return a.$.tab('show');
            }
          }
        });
        tabContentClass = 'tab-pane ' + tabClass;
        ret.add(tabName, content.make('div', {
          props: {
            "class": tabContentClass,
            id: tabName
          }
        }));
      });
      return ret;
    });
  })((typeof global !== 'undefined' && global ? global : (typeof window !== 'undefined' ? window : this)).OJ);

}).call(this);

//# sourceMappingURL=tabs.js.map