// Generated by CoffeeScript 1.7.1
(function() {
  (function(OJ) {
    var className, nodeName;
    nodeName = 'x-tile';
    className = 'tile';
    OJ.components.members[className] = nodeName;
    OJ.components.register(className, function(options, owner) {
      var defaults, ret;
      defaults = {
        width: {
          xs: '',
          sm: '',
          md: '',
          lg: ''
        },
        props: {
          "class": 'tile'
        }
      };
      OJ.extend(defaults, options, true);
      if (defaults.width.xs) {
        defaults.props["class"] += ' col-xs-' + defaults.width.xs;
      }
      if (defaults.width.sm) {
        defaults.props["class"] += ' col-sm-' + defaults.width.sm;
      }
      if (defaults.width.md) {
        defaults.props["class"] += ' col-md-' + defaults.width.md;
      }
      if (defaults.width.lg) {
        defaults.props["class"] += ' col-lg-' + defaults.width.lg;
      }
      ret = OJ.component(defaults, owner, nodeName);
      return ret;
    });
  })((typeof global !== 'undefined' && global ? global : (typeof window !== 'undefined' ? window : this)).OJ);

}).call(this);

//# sourceMappingURL=tile.js.map