// Generated by CoffeeScript 1.7.1
(function() {
  (function(OJ) {
    module(OJ.name + 'node');
    test(OJ.name + '.nodes.div(TestingDiv)', function() {
      var node;
      node = OJ.nodes.div();
      node.text('Hi I\'m some text');
      deepEqual(node.tagName === 'div', true, OJ.name + ' Node is a DIV');
    });
    test(OJ.name + ' test child node', function() {
      var childDiv, node;
      node = OJ.nodes.div();
      node.text('Hi I\'m some nu text');
      childDiv = node.div();
      childDiv.text('Hi I\'m some child text');
      deepEqual(childDiv.tagName === 'div', true, OJ.name + ' Node is a DIV');
    });
  })((typeof global !== 'undefined' && global ? global : (typeof window !== 'undefined' ? window : this)).OJ);

}).call(this);

//# sourceMappingURL=test.node.map
