// Generated by CoffeeScript 1.7.1
(function() {
  var _listenerIIFE;

  (_listenerIIFE = function(OJ) {

    /*
    Define the subscriber methods which are available to this class.
     */
    var sheetSubscribers, subscribers;
    sheetSubscribers = OJ.object();
    sheetSubscribers.add("beforeclose", "beforeclose");
    sheetSubscribers.add("beforeshow", "beforeshow");
    sheetSubscribers.add("show", "show");
    OJ.constant(OJ.sheets, "subscribers", sheetSubscribers);

    /*
    Create a new subscribers collection. This returns a subscribers object with an add method.
     */
    OJ.sheets.subscribers.register("subscribers", subscribers = function() {
      "use strict";
      var ret;
      ret = OJ.makeSubscribers("sheetSubscribers", "sheets");
      return ret;
    });
  })((typeof global !== "undefined" && global ? global : (typeof window !== "undefined" ? window : this)).OJ);

}).call(this);

//# sourceMappingURL=_sheetSubscribers.map
