// Generated by CoffeeScript 1.7.1
(function() {
  var _showIIFE;

  (_showIIFE = function(OJ) {

    /*
    Create a new show subscriber;
     */
    var subscribers;
    OJ.sheets.subscribers.register("show", subscribers = function(callBack) {
      var show;
      if (callBack) {

        /*
        Show event on the tree panel
        @param extView {Ext.Component} usually the Ext Window
        @param eOpts {Object} arbitrary Ext props
         */
        return show = function(extView, eOpts) {
          var args;
          args = arguments_;
          return OJ.fun.apply(callBack, args, this);
        };
      }
    });
  })((typeof global !== "undefined" && global ? global : (typeof window !== "undefined" ? window : this)).OJ);

}).call(this);

//# sourceMappingURL=show.map
