// Generated by CoffeeScript 1.7.1
(function() {
  (function() {
    "use strict";
    OJ.cookie.register("cookieNames", {});
    OJ.cookie.register("get", function(cookiename) {
      var cookie, ret;
      cookie = $.cookie(cookiename);
      ret = "";
      if (cookie !== "[object Object]") {
        ret = OJ.string(cookie);
      }
      return ret;
    });
    OJ.cookie.register("set", function(cookiename, value) {
      return $.cookie(cookiename, value);
    });
    OJ.cookie.register("clear", function(cookiename) {
      return $.cookie(cookiename, "");
    });
    OJ.cookie.register("clearAll", function(exceptions) {
      var preserveThese;
      preserveThese = [];
      exceptions = exceptions || [];
      OJ.iterate(exceptions, function(cookieName) {
        var val;
        val = OJ.cookie.get(cookieName);
        if (false === OJ.isNullOrEmpty(val)) {
          preserveThese.push({
            name: cookieName,
            val: val
          });
        }
      });
      OJ.iterate(OJ.cookie.cookieNames, function(name) {
        $.cookie(name, null);
      });
      OJ.iterate($.cookie(), function(name) {
        $.cookie(name, null);
      });
      OJ.iterate(preserveThese, function(cook) {
        OJ.cookie.set(cook.name, cook.val);
      });
      return true;
    });
  })();

}).call(this);

//# sourceMappingURL=cookie.map
