// Generated by CoffeeScript 1.7.1
(function() {
  (function() {
    var makePubSubMethods;
    makePubSubMethods = function(privateBindingObj, nameSpace) {
      privateBindingObj = privateBindingObj || $({});
      nameSpace.register("subscribe", function() {
        privateBindingObj.on.apply(privateBindingObj, arguments);
      });
      nameSpace.register("unsubscribe", function() {
        privateBindingObj.off.apply(privateBindingObj, arguments);
      });
      nameSpace.register("publish", function() {
        privateBindingObj.trigger.apply(privateBindingObj, arguments);
      });
      nameSpace.register("pubsSubs", function() {
        var ret;
        ret = {};
        if (OJ.session.isDebug()) {
          OJ.iterate(privateBindingObj[0], function(prop, key) {
            if (prop.events) {
              ret = prop.events;
              return false;
            }
          });
        }
        return ret;
      });
    };
    "use strict";
    makePubSubMethods($({}), OJ);
    makePubSubMethods($({}), OJ.properties);
    OJ.register("scopeNewPubSubBindings", makePubSubMethods);
  })();

}).call(this);

//# sourceMappingURL=pubsub.map
