// Generated by CoffeeScript 1.7.1
(function() {
  (function(OJ) {
    "use strict";
    var inheritsFrom, onError;
    onError = window.onerror;

    /*
    Log errors to the console
     */
    window.onerror = function(msg, url, lineNumber) {
      console.warn("%s\rurl: %s\rline: %d", msg, url, lineNumber);
      if (onError) {
        onError(arguments);
      }
      return false;
    };
    if (!window.setImmediate) {

      /*
      Shim for setImmediate
       */
      window.setImmediate = function(func, args) {
        return window.setTimeout(func, 0, args);
      };
      window.clearImmediate = window.clearTimeout;
    }
    if (!Function.prototype.inheritsFrom) {
      Object.defineProperties(Function.prototype, {
        inheritsFrom: {

          /*
          Easy inheritance by prototype
           */
          value: inheritsFrom = function(parentClassOrObject) {
            if (parentClassOrObject.constructor === Function) {
              this.prototype = new parentClassOrObject;
              this.prototype.constructor = this;
              this.prototype.parent = parentClassOrObject.prototype;
            } else {
              this.prototype = parentClassOrObject;
              this.prototype.constructor = this;
              this.prototype.parent = parentClassOrObject;
            }
            return this;
          }
        }
      });
    }
  })((typeof global !== "undefined" && global ? global : (typeof window !== "undefined" ? window : this)).OJ);

}).call(this);

//# sourceMappingURL=shims.map
