// Generated by CoffeeScript 1.7.1
(function() {
  (function(OJ) {
    module('nodes');
    test('Test the Div node', function() {
      var cNode, child, childId, dNode, node, nodeId;
      expect(7);
      node = OJ.nodes.div();
      node.text('Hi I\'m some text');
      deepEqual(node.tagName === 'div', true, 'Node is a DIV');
      nodeId = node.getId();
      dNode = document.getElementById(nodeId);
      ok(dNode, 'Node is in the DOM');
      deepEqual(nodeId, dNode.id, 'Element IDs are equal');
      child = node.div();
      childId = child.getId();
      deepEqual(child.tagName === 'div', true, 'Node is a DIV');
      cNode = document.getElementById(childId);
      deepEqual(cNode.id, childId, 'Element IDs are equal');
      node.remove();
      equal(undefined, document.getElementById(nodeId, 'Node has been removed'));
      equal(undefined, document.getElementById(childId, 'Child has been removed'));
    });
    test('Test the Span node', function() {
      var cNode, child, childId, dNode, node, nodeId;
      expect(7);
      node = OJ.nodes.span();
      node.text('Hi I\'m some text');
      deepEqual(node.tagName === 'span', true, 'Node is a span');
      nodeId = node.getId();
      dNode = document.getElementById(nodeId);
      ok(dNode, 'Node is in the DOM');
      deepEqual(nodeId, dNode.id, 'Element IDs are equal');
      child = node.span();
      childId = child.getId();
      deepEqual(child.tagName === 'span', true, 'Node is a span');
      cNode = document.getElementById(childId);
      deepEqual(cNode.id, childId, 'Element IDs are equal');
      node.remove();
      equal(undefined, document.getElementById(nodeId, 'Node has been removed'));
      equal(undefined, document.getElementById(childId, 'Child has been removed'));
    });
    test('Test the Table node', function() {
      var cNode, child, childId, dNode, i, node, nodeId;
      expect(25);
      node = OJ.nodes.table();
      deepEqual(node.tagName === 'table', true, 'Node is a table');
      nodeId = node.getId();
      dNode = document.getElementById(nodeId);
      ok(dNode, 'Node is in the DOM');
      deepEqual(nodeId, dNode.id, 'Element IDs are equal');
      i = 0;
      while (i < 10) {
        child = node.cell(Faker.random.number(99), Faker.random.number(99));
        childId = child.getId();
        deepEqual(child.tagName === "td", true, "Node is a td");
        cNode = document.getElementById(childId);
        deepEqual(cNode.id, childId, 'Element IDs are equal');
        i += 1;
      }
      node.remove();
      equal(undefined, document.getElementById(nodeId, 'Node has been removed'));
      equal(undefined, document.getElementById(childId, 'Child has been removed'));
    });
  })((typeof global !== 'undefined' && global ? global : (typeof window !== 'undefined' ? window : this)).OJ);

}).call(this);

//# sourceMappingURL=test.nodes.map
