// Generated by CoffeeScript 1.7.1
(function() {
  (function(OJ) {
    OJ.async.register('ajaxPromise', function(ajax) {
      var promise;
      promise = Q.when(ajax);
      promise.abort = ajax.abort;
      promise.readyState = ajax.readyState;
      return promise;
    });
    OJ.async.register('all', function(initArray) {
      var promise, reqs;
      reqs = initArray || [];
      promise = Q.all(reqs);
      promise.push = function(item) {
        reqs.push(item);
      };
      return promise;
    });
    OJ.async.register('defer', function(func) {
      var ret;
      if (func == null) {
        func = OJ.noop;
      }
      ret = Q.fcall(func);
      return ret;
    });
    OJ.async.register('promise', function(deferred) {
      var ret;
      if (deferred == null) {
        deferred = Q.defer();
      }
      if (deferred && deferred.promise) {
        return ret = deferred.promise;
      }
    });
  })((typeof global !== 'undefined' && global ? global : (typeof window !== 'undefined' ? window : this)).OJ);

}).call(this);

//# sourceMappingURL=promise.js.map