// Generated by CoffeeScript 1.7.1
(function() {
  (function(OJ) {
    OJ.async.register('ajaxPromise', function(ajax) {
      var promise;
      promise = Q.when(ajax);
      promise.abort = ajax.abort;
      promise.readyState = ajax.readyState;
      return promise;
    });
    OJ.async.register('all', function(initArray) {
      var promise, reqs;
      reqs = initArray || [];
      promise = Q.all(reqs);
      promise.push = function(item) {
        reqs.push(item);
      };
      return promise;
    });
    OJ.async.register('defer', function() {
      var ret;
      ret = Q.defer();
      return ret;
    });
  })((typeof global !== 'undefined' && global ? global : (typeof window !== 'undefined' ? window : this)).OJ);

}).call(this);

//# sourceMappingURL=promise.js.map