// Generated by CoffeeScript 1.7.1
(function() {
  var _listenerIIFE;

  (_listenerIIFE = function(OJ) {

    /*
    Define the subscriber methods which are available to this class.
     */
    var gridSubscribeableEvents, subscribers;
    gridSubscribeableEvents = OJ.object();
    gridSubscribeableEvents.render = "render";
    gridSubscribeableEvents.drop = "drop";
    gridSubscribeableEvents.bodyscroll = "bodyscroll";
    OJ.constant(OJ.grids, "subscribers", gridSubscribeableEvents);

    /*
    Create a new subscribers collection. This returns a subscribers object with an add method.
     */
    OJ.grids.subscribers.register("subscribers", subscribers = function() {
      var ret;
      ret = OJ.makeSubscribers("gridSubscribers", "grids");
      return ret;
    });
  })((typeof global !== "undefined" && global ? global : (typeof window !== "undefined" ? window : this)).OJ);

}).call(this);

//# sourceMappingURL=_gridSubscribers.map
