// Generated by CoffeeScript 1.7.1
(function() {
  var _renderIIFE;

  (_renderIIFE = function(OJ) {

    /*
    Create a new render subscriber;
     */
    var subscribers;
    OJ.grids.subscribers.register("render", subscribers = function(callBack) {
      var render;
      if (callBack) {

        /*
        Render event on the grid panel
        @param extView {Ext.Component} usually the Ext Panel
        @param eOpts {Object} arbitrary Ext props
         */
        return render = function(extView, eOpts) {
          var args;
          args = arguments_;
          return OJ.fun.apply(callBack, args, this);
        };
      }
    });
  })((typeof global !== "undefined" && global ? global : (typeof window !== "undefined" ? window : this)).OJ);

}).call(this);

//# sourceMappingURL=render.map
