// Generated by CoffeeScript 1.7.1
(function() {
  (function(OJ) {
    var tables;
    tables = function(select) {
      var ret;
      ret = new OJ.actions.querybuilder.SqlTableNameStore({
        storeId: "SqlTableNameStore"
      });
      ret.handleSQLTableUpdate = function(tableStore, table, operation) {
        if (operation === "commit") {
          select.fields.updateFieldTableData(table);
          select.joins.updateJoinTableData(table);
          select.updateSQLOutput();
        }
      };
      ret.handleSQLTableAdd = function(tableStore, table, index) {
        select.updateSQLOutput();
      };
      ret.handleSQLTableRemove = function(tableStore, table, index) {
        var aJoins, i, l;
        aJoins = [];
        aJoins = select.joins.getJoinsByTableId(table.get("id"));
        i = 0;
        l = aJoins.length;
        while (i < l) {
          select.joins.removeJoinById(aJoins[i].get("id"));
          i++;
        }
        select.updateSQLOutput();
      };
      ret.on("update", ret.handleSQLTableUpdate, select);
      ret.on("add", ret.handleSQLTableAdd, select);
      ret.on("remove", ret.handleSQLTableRemove, select);
      ret.addTable = function(table) {
        ret.add(table);
        return ret;
      };
      ret.removeTableById = function(tableID) {
        var table;
        table = void 0;
        table = ret.getById(tableID);
        ret.remove(table);
        return ret;
      };
      ret.getTableById = function(tableID) {
        return ret.getById(tableID);
      };
      return ret;
    };
    OJ.actions.sql.register("tables", tables);
  })((typeof global !== "undefined" && global ? global : (typeof window !== "undefined" ? window : this)).OJ);

}).call(this);

//# sourceMappingURL=tables.map
