// Generated by CoffeeScript 1.7.1
(function() {
  (function(OJ) {

    /*
    Create an HTML Element through ThinDom
     */
    var component;
    component = function(options, owner, tagName) {
      var ret, widget;
      if (options == null) {
        options = OJ.object();
      }
      if (!tagName.startsWith('x-')) {
        tagName = 'x-' + tagName;
      }
      widget = OJ.element(tagName, options.props, options.styles, options.events, options.text);
      OJ.nodes.factory(widget, owner);
      ret = widget.div();
      ret.add('componentName', tagName);
      return ret;
    };
    OJ.register('component', component);
  })((typeof global !== 'undefined' && global ? global : (typeof window !== 'undefined' ? window : this)).OJ);

}).call(this);

//# sourceMappingURL=component.map
