// Generated by CoffeeScript 1.7.1
(function() {
  (function(OJ) {

    /*
    Create a set of HTML Elements through ThinDom
     */
    var control;
    control = function(options, owner, tagName) {
      var ret, rootNodeType;
      if (options == null) {
        options = OJ.object();
      }
      if (!tagName.startsWith('y-')) {
        tagName = 'y-' + tagName;
      }
      rootNodeType = options.rootNodeType || OJ['DEFAULT_COMPONENT_ROOT_NODETYPE'] || 'div';
      ret = OJ.element(rootNodeType, options.props, options.styles, options.events, options.text);
      OJ.nodes.factory(ret, owner);
      ret.add('controlName', tagName);
      return ret;
    };
    OJ.register('control', control);
  })((typeof global !== 'undefined' && global ? global : (typeof window !== 'undefined' ? window : this)).OJ);

}).call(this);

//# sourceMappingURL=control.js.map