// Generated by CoffeeScript 1.7.1
(function() {
  (function(OJ) {

    /*
    Create an OJ Input Object through OJ.nodes.input
     */
    var input;
    input = function(options, owner) {
      var ret;
      if (options == null) {
        options = OJ.object();
      }
      if (!owner) {
        throw new Error('Cannot create an input without a parent');
      }
      if (!options.props || !options.props.type) {
        throw new Error('Cannot create an input without an input type');
      }
      ret = owner.input(options);
      ret.add('inputName', options.props.type);
      return ret;
    };
    OJ.register('input', input);
  })((typeof global !== 'undefined' && global ? global : (typeof window !== 'undefined' ? window : this)).OJ);

}).call(this);

//# sourceMappingURL=input.js.map