// Generated by CoffeeScript 1.7.1
(function() {
  (function(OJ) {
    var addComponents, closed, controlPostProcessing, extendChain, initBody, isBodyDefined, isChildNodeTypeAllowed, nestableNodeNames, nonNestableNodes, open;
    closed = 'a abbr acronym address applet article aside audio b bdo big blockquote body button canvas caption center cite code colgroup command datalist dd del details dfn dir div dl dt em embed fieldset figcaption figure font footer form frameset h1 h2 h3 h4 h5 h6 head header hgroup html i iframe ins keygen kbd label legend li map mark menu meter nav noframes noscript object ol optgroup option output p pre progress q rp rt ruby s samp script section select small source span strike strong style sub summary sup table tbody td textarea tfoot th thead time title tr tt u ul var video wbr xmp'.split(' ');
    open = 'area base br col command css !DOCTYPE embed hr img input keygen link meta param source track wbr'.split(' ');
    nestableNodeNames = ['div', 'span', 'h1', 'h2', 'h3', 'h4', 'h5', 'h6', 'p', 'fieldset', 'select', 'ol', 'ul', 'table'];
    nonNestableNodes = ['li', 'legend', 'tr', 'td', 'option', 'body', 'head', 'source', 'tbody', 'tfoot', 'thead', 'link', 'script'];
    isChildNodeTypeAllowed = function(parent, tagName) {
      var allowed;
      switch (parent.tagName) {
        case 'a':
          allowed = false === _.contains(nonNestableNodes, tagName);
          break;
        case 'body':
          allowed = (tagName.startsWith('x-')) || _.contains(nestableNodeNames, tagName);
          break;
        case 'div':
          allowed = false === _.contains(nonNestableNodes, tagName);
          break;
        case 'form':
          allowed = false === _.contains(nonNestableNodes, tagName);
          break;
        case 'label':
          allowed = false === _.contains(nonNestableNodes, tagName);
          break;
        case 'legend':
          allowed = false;
          break;
        case 'fieldset':
          allowed = tagName === 'legend' || false === _.contains(nonNestableNodes, tagName);
          break;
        case 'ol':
          allowed = tagName === 'li';
          break;
        case 'ul':
          allowed = tagName === 'li';
          break;
        case 'li':
          allowed = false === _.contains(nonNestableNodes, tagName);
          break;
        case 'table':
          allowed = tagName === 'td' || tagName === 'tr' || tagName === 'tbody';
          break;
        case 'td':
          allowed = false === _.contains(nonNestableNodes, tagName);
          break;
        case 'select':
          allowed = tagName === 'option';
          break;
        case 'option':
          allowed = false;
          break;
        case 'span':
          allowed = false === _.contains(nonNestableNodes, tagName);
          break;
        case 'p':
          allowed = false === _.contains(nonNestableNodes, tagName);
          break;
        default:
          if (parent.tagName.startsWith('x-')) {
            allowed = false === _.contains(nonNestableNodes, tagName);
          } else {
            allowed = false;
          }
      }
      return allowed;
    };

    /*
    Add components to the chain, if permitted
    @tagName is the web component compatible node name (e.g. x-widget)
    @className is the internal, developer friendly name (e.g widget)
     */
    addComponents = function(tagName, parent, count, className) {
      if (isChildNodeTypeAllowed(parent, tagName)) {
        return parent.add(className, function(opts) {
          var nu;
          if (OJ.components[className]) {
            nu = OJ.components[className](opts, parent, true);
          } else {
            nu = OJ.component(className, parent);
          }
          return nu;
        });
      }
    };

    /*
    Determine which components to add to chain, if any
     */
    controlPostProcessing = function(parent, count) {
      if (_.contains(['div', 'span', 'td', 'p', 'body', 'form', 'li'], parent.tagName)) {
        OJ.each(OJ.components.members, function(className, tagName) {
          return addComponents(tagName, parent, count, className);
        });
      }
    };

    /*
    Extend the chain, if permitted
     */
    extendChain = function(tagName, parent, count) {
      if (isChildNodeTypeAllowed(parent, tagName)) {
        return parent.add(tagName, function(opts) {
          var nu;
          if (OJ.nodes[tagName]) {
            nu = OJ.nodes[tagName](opts, parent, true);
          } else if ((_.contains(closed, tagName)) || _.contains(open, tagName)) {
            nu = OJ.element(tagName, parent);
          }
          return OJ.nodes.factory(nu, parent, count);
        });
      }
    };

    /*
    Init the body for chaining the first time it's seen
     */
    initBody = _.once(function(body) {
      body.count = 0;
      return OJ.nodes.factory(body, null, 0);
    });
    isBodyDefined = false;
    OJ.nodes.register('factory', function(el, parent, count) {
      var id, ret;
      if (parent == null) {
        parent = OJ.body;
      }
      if (count == null) {
        count = parent.count || 0;
      }
      if (!el.isFullyInit) {
        initBody(OJ.body);
        count += 1;
        if (el.tagName === 'body' && !isBodyDefined) {
          parent = null;
          el.root = null;
          ret = OJ.dom(el, null);
          controlPostProcessing(ret, 0);
          isBodyDefined = true;
        } else {
          parent.count = count;
          ret = OJ.dom(el, parent);
          if (!ret.isInDOM) {
            if (!ret.getId()) {
              id = parent.getId();
              id += ret.tagName + count;
              ret.attr('id', id);
            }
            parent.append(ret[0]);
            ret.isInDOM = true;
          }
          controlPostProcessing(ret, count);
        }
        ret.isFullyInit = true;
        extendChain('a', ret, count);
        extendChain('b', ret, count);
        extendChain('br', ret, count);
        extendChain('button', ret, count);
        extendChain('div', ret, count);
        extendChain('em', ret, count);
        extendChain('fieldset', ret, count);
        extendChain('form', ret, count);
        extendChain('h1', ret, count);
        extendChain('h2', ret, count);
        extendChain('h3', ret, count);
        extendChain('h4', ret, count);
        extendChain('h5', ret, count);
        extendChain('h6', ret, count);
        extendChain('i', ret, count);
        extendChain('img', ret, count);
        extendChain('input', ret, count);
        extendChain('label', ret, count);
        extendChain('legend', ret, count);
        extendChain('li', ret, count);
        extendChain('nav', ret, count);
        extendChain('ol', ret, count);
        extendChain('option', ret, count);
        extendChain('p', ret, count);
        extendChain('select', ret, count);
        extendChain('span', ret, count);
        extendChain('strong', ret, count);
        extendChain('sup', ret, count);
        extendChain('svg', ret, count);
        extendChain('table', ret, count);
        extendChain('tbody', ret, count);
        extendChain('td', ret, count);
        extendChain('textarea', ret, count);
        extendChain('thead', ret, count);
        extendChain('tr', ret, count);
        extendChain('ul', ret, count);
      }
      return ret;
    });
  })((typeof global !== 'undefined' && global ? global : (typeof window !== 'undefined' ? window : this)).OJ);

}).call(this);

//# sourceMappingURL=nodeFactory.map
