// Generated by CoffeeScript 1.7.1
(function() {
  (function(OJ) {
    var addComponents, buildNodeForChaining, closed, initBody, nestableNodeNames, nodeNames, nonNestableNodes, open;
    closed = 'a abbr acronym address applet article aside audio b bdo big blockquote body button canvas caption center cite code colgroup command datalist dd del details dfn dir div dl dt em embed fieldset figcaption figure font footer form frameset h1 h2 h3 h4 h5 h6 head header hgroup html i iframe ins keygen kbd label legend li map mark menu meter nav noframes noscript object ol optgroup option output p pre progress q rp rt ruby s samp script section select small source span strike strong style sub summary sup table tbody td textarea tfoot th thead time title tr tt u ul var video wbr xmp'.split(' ');
    open = 'area base br col command css !DOCTYPE embed hr img input keygen link meta param source track wbr'.split(' ');
    nestableNodeNames = ['div', 'span', 'h1', 'h2', 'h3', 'h4', 'h5', 'h6', 'p', 'fieldset', 'select', 'ol', 'ul', 'table'];
    nonNestableNodes = ['li', 'legend', 'tr', 'td', 'option', 'body', 'head', 'source', 'tbody', 'tfoot', 'thead', 'link', 'script'];

    /*
    Add components to the chain, if permitted
    @tagName is the web component compatible node name (e.g. x-widget)
    @className is the internal, developer friendly name (e.g widget)
     */
    addComponents = function(tagName, parent, count, className, nameSpace) {
      if (nameSpace == null) {
        nameSpace = 'components';
      }
      parent.add(className, function(opts) {
        var nu;
        if (OJ[nameSpace][className]) {
          nu = OJ[nameSpace][className](opts, parent, true);
        } else {
          nu = OJ.component(className, parent);
        }
        return nu;
      });
    };

    /*
    Init the body for chaining the first time it's seen
     */
    initBody = _.once(function(body) {
      body.count = 0;
      body.root = null;
      OJ.dom(body, null);
      buildNodeForChaining(body, 0);
      body.isFullyInit = true;
      return body;
    });

    /*
    Fetch a node from the DOM and return an OJ'fied instance of the element
     */
    OJ.nodes.register('get', function(id, tagName) {
      var el, ret, thinEl;
      if (tagName == null) {
        tagName = 'div';
      }
      ret = null;
      el = document.getElementById(id);
      if (el) {
        thinEl = OJ.restoreElement(tagName, el);
      }
      if (thinEl) {
        ret = OJ.nodes.factory(thinEl, null, 0);
      }
      return ret;
    });
    nodeNames = ['a', 'b', 'br', 'button', 'div', 'em', 'fieldset', 'form', 'h1', 'h2', 'h3', 'h4', 'h5', 'h6', 'i', 'img', 'input', 'label', 'legend', 'li', 'nav', 'ol', 'option', 'p', 'select', 'span', 'strong', 'sup', 'svg', 'table', 'tbody', 'td', 'textarea', 'th', 'thead', 'tr', 'ul'];
    buildNodeForChaining = function(el, count) {
      OJ.each(nodeNames, function(tagName) {
        return el.add(tagName, function(opts) {
          var nu;
          if (OJ.nodes[tagName]) {
            nu = OJ.nodes[tagName](opts, el, true);
          } else if ((_.contains(closed, tagName)) || _.contains(open, tagName)) {
            nu = OJ.element(tagName, el);
          }
          return OJ.nodes.factory(nu, el, count);
        });
      });
      OJ.each(OJ.components.members, function(className, tagName) {
        return addComponents(tagName, parent, count, className);
      });
      OJ.each(OJ.controls.members, function(className, tagName) {
        return addComponents(tagName, el, count, className, 'controls');
      });
      OJ.each(OJ.inputs.members, function(className, tagName) {
        return addComponents(tagName, el, count, className, 'inputs');
      });
      return el;
    };

    /*
    Extends a OJ Control class with all the (permitted) methods on the factory
     */
    OJ.nodes.register('factory', function(el, parent, count) {
      var id, ret;
      if (parent == null) {
        parent = OJ.body;
      }
      if (count == null) {
        count = parent.count || 0;
      }
      initBody(OJ.body);
      ret = el;
      if (!el.isFullyInit) {
        count += 1;
        if (count <= parent.count) {
          count = parent.count + 1;
        }
        parent.count = count;
        if (el.tagName !== 'body') {
          ret = OJ.dom(el, parent);
          if (!ret.isInDOM) {
            if (OJ.GENERATE_UNIQUE_IDS) {
              if (!ret.getId()) {
                id = parent.getId();
                id += ret.tagName + count;
                ret.attr('id', id);
              }
            }
            parent.append(ret[0]);
            ret.bindEvents();
            ret.isInDOM = true;
          }
          buildNodeForChaining(ret, count);
          ret.isFullyInit = true;
        }
      }
      return ret;
    });
  })((typeof global !== 'undefined' && global ? global : (typeof window !== 'undefined' ? window : this)).OJ);

}).call(this);

//# sourceMappingURL=nodeFactory.js.map