// Generated by CoffeeScript 1.7.1
(function() {
  (function(OJ) {
    module('pubSub');
    asyncTest('Test pubsub', function() {
      var method;
      expect(1);
      method = function() {
        ok(true, 'Event was successfully called');
        return start();
      };
      OJ.subscribe('PubSub Test', method);
      OJ.publish('PubSub Test');
    });
  })((typeof global !== 'undefined' && global ? global : (typeof window !== 'undefined' ? window : this)).OJ);

}).call(this);

//# sourceMappingURL=test.pubsub.map
