// Generated by CoffeeScript 1.7.1
(function() {
  (function(OJ) {
    'use strict';
    OJ.nodes.register('table', function(options, owner, calledFromFactory) {
      var defaults, init, isInit, ret, rows, tbody;
      if (owner == null) {
        owner = OJ.body;
      }
      if (calledFromFactory == null) {
        calledFromFactory = false;
      }
      defaults = {
        props: {
          cellpadding: 0,
          cellspacing: 0,
          align: "",
          width: "",
          cellalign: "left",
          cellvalign: "top"
        },
        styles: {},
        events: {
          click: _.noop
        },
        cells: {
          "class": "",
          align: '',
          'vertical-align': '',
          cellpadding: '',
          margin: ''
        },
        firstAlignRight: false,
        oddAlignRight: false
      };
      rows = [];
      OJ.extend(defaults, options);
      ret = OJ.element('table', defaults.props, defaults.styles, defaults.events);
      tbody = null;
      isInit = false;
      init = function() {
        tbody = OJ.nodes.tbody({}, ret, false);
        rows.push(OJ.nodes.tr({}, tbody, false));
      };
      ret.add('cell', function(rowNo, colNo) {
        var cell, row;
        if (false === isInit) {
          init();
          isInit = true;
        }
        if (rowNo < 1) {
          rowNo = 1;
        }
        if (colNo < 1) {
          colNo = 1;
        }
        row = rows[rowNo];
        if (!row) {
          while (rows.length < rowNo) {
            row = OJ.nodes.tr({}, tbody, false);
            rows.push(row);
          }
        }
        cell = row[0].cells[colNo];
        if (!cell) {
          while (row[0].cells.length < colNo) {
            cell = OJ.nodes.td({
              props: defaults.cells
            }, row, false);
          }
        }
        if (!cell.isValid) {
          OJ.nodes.factory(cell, row, rowNo + colNo);
        }
        return cell;
      });
      if (owner) {
        owner.append(ret[0]);
      }
      if (false === calledFromFactory) {
        OJ.nodes.factory(ret, owner);
      }
      return ret;
    });
  })((typeof global !== 'undefined' && global ? global : (typeof window !== 'undefined' ? window : this)).OJ);

}).call(this);

//# sourceMappingURL=table.map
