// Generated by CoffeeScript 1.7.1
(function() {
  (function(OJ) {
    module('x-tabs', {
      setup: function() {
        OJ['GENERATE_UNIQUE_IDS'] = true;
        if (!OJ.body.make) {
          return OJ.nodes.div();
        }
      }
    });
    test('Test the tabs component', function() {
      var dNode, nodeId, tabs;
      expect(4);
      tabs = OJ.body.make('tabs', {
        tabs: {
          tabA: 'tabA',
          tabB: 'tabB'
        }
      });
      deepEqual(tabs.componentName === 'x-tabs', true, 'Component is a tabs');
      nodeId = tabs.getId();
      dNode = document.getElementById(nodeId);
      ok(dNode, 'Node is in the DOM');
      deepEqual(nodeId, dNode.id, 'Element IDs are equal');
      tabs.remove();
      equal(undefined, document.getElementById(nodeId, 'tabs has been removed'));
    });
  })((typeof global !== 'undefined' && global ? global : (typeof window !== 'undefined' ? window : this)).OJ);

}).call(this);

//# sourceMappingURL=test.tabs.map
