// Generated by CoffeeScript 1.7.1
(function() {
  (function(OJ) {
    module('x-address', {
      setup: function() {
        OJ['GENERATE_UNIQUE_IDS'] = true;
        return OJ.nodes.div();
      }
    });
    test('Test the address component', function() {
      var address, dNode, nodeId;
      expect(4);
      address = OJ.body.address();
      deepEqual(address.componentName === 'x-address', true, 'Component is an address');
      nodeId = address.getId();
      dNode = document.getElementById(nodeId);
      ok(dNode, 'Node is in the DOM');
      deepEqual(nodeId, dNode.id, 'Element IDs are equal');
      address.remove();
      equal(undefined, document.getElementById(nodeId, 'Address has been removed'));
    });
  })((typeof global !== 'undefined' && global ? global : (typeof window !== 'undefined' ? window : this)).OJ);

}).call(this);

//# sourceMappingURL=test.address.js.map