// Generated by CoffeeScript 1.7.1
(function() {
  (function(OJ) {
    module('x-price', {
      setup: function() {
        OJ['GENERATE_UNIQUE_IDS'] = true;
        return OJ.nodes.div();
      }
    });
    test('Test the price component', function() {
      var dNode, nodeId, price;
      expect(4);
      price = OJ.body.price();
      deepEqual(price.componentName === 'x-price', true, 'Component is a price');
      nodeId = price.getId();
      dNode = document.getElementById(nodeId);
      ok(dNode, 'Node is in the DOM');
      deepEqual(nodeId, dNode.id, 'Element IDs are equal');
      price.remove();
      equal(undefined, document.getElementById(nodeId, 'Price has been removed'));
    });
  })((typeof global !== 'undefined' && global ? global : (typeof window !== 'undefined' ? window : this)).OJ);

}).call(this);

//# sourceMappingURL=test.price.map
