// Generated by CoffeeScript 1.7.1
(function() {
  (function(OJ) {
    'use strict';
    var nodeName;
    nodeName = 'br';
    OJ.nodes.register(nodeName, function(options, owner, calledFromFactory) {
      var defaults, i, ret;
      if (owner == null) {
        owner = OJ.body;
      }
      if (calledFromFactory == null) {
        calledFromFactory = false;
      }
      defaults = {
        props: {},
        styles: {},
        events: {
          click: OJ.noop
        },
        number: 1
      };
      OJ.extend(defaults, options, true);
      i = 0;
      while (i < OJ.to.number(defaults.number)) {
        ret = OJ.element(nodeName, defaults.props, defaults.styles, defaults.events, defaults.text);
        i += 1;
      }
      if (false === calledFromFactory) {
        OJ.nodes.factory(ret, owner);
      }
      return ret;
    });
  })((typeof global !== 'undefined' && global ? global : (typeof window !== 'undefined' ? window : this)).OJ);

}).call(this);

//# sourceMappingURL=br.js.map