// Generated by CoffeeScript 1.7.1
(function() {
  var _listenerIIFE;

  (_listenerIIFE = function(OJ) {

    /*
    Define the subscriber methods which are available to this class.
     */
    var subscribers, treeSubscribers;
    treeSubscribers = Object.create(null);
    treeSubscribers.afterrender = "afterrender";
    treeSubscribers.itemdblclick = "itemdblclick";
    OJ.constant(OJ.trees, "subscribers", treeSubscribers);

    /*
    Create a new subscribers collection. This returns a subscribers object with an add method.
     */
    OJ.trees.subscribers.register("subscribers", subscribers = function() {
      "use strict";
      var ret;
      ret = OJ.makeSubscribers("treeSubscribers", "trees");
      return ret;
    });
  })((typeof global !== "undefined" && global ? global : (typeof window !== "undefined" ? window : this)).OJ);

}).call(this);

//# sourceMappingURL=_treeSubscribers.map
