// Generated by CoffeeScript 1.7.1
(function() {
  var _itemdbclickIIFE;

  (_itemdbclickIIFE = function(OJ) {

    /*
    Create a new render subscriber;
     */
    var subscribers;
    OJ.trees.subscribers.register("itemdblclick", subscribers = function(callBack) {
      "use strict";
      var itemdblclick;
      if (callBack) {

        /*
        AfterRender event on the tree panel
        @param extView {Ext.Component} usually the Ext Panel
        @param record {Ext.data.Model} The record object
        @param item {HTMLElement} The DOM node
        @param e {Ext.EventObject} The event object
        @param eOpts {Object} arbitrary Ext props
         */
        return itemdblclick = function(extView, record, item, index, e, eOpts) {
          "use strict";
          callBack(extView, record, item, index, e, eOpts);
        };
      }
    });
  })((typeof global !== "undefined" && global ? global : (typeof window !== "undefined" ? window : this)).OJ);

}).call(this);

//# sourceMappingURL=itemdbclick.map
