// Generated by CoffeeScript 1.7.1
(function() {
  var __slice = [].slice;

  (function(OJ) {
    var console, methodLength, methods;
    methods = ['assert', 'clear', 'count', 'debug', 'dir', 'dirxml', 'error', 'exception', 'group', 'groupCollapsed', 'groupEnd', 'info', 'log', 'memory', 'profile', 'profileEnd', 'table', 'time', 'timeEnd', 'timeStamp', 'timeline', 'timelineEnd', 'trace', 'warn'];
    methodLength = methods.length;
    console = OJ.global.console || {};
    OJ.makeSubNameSpace('console');

    /*
    1. Stub out any missing methods with noop
    2. Define the available methods on the OJ.console object
     */
    while (methodLength--) {
      (function() {
        var method;
        method = methods[methodLength];
        if (!console[method]) {
          console[method] = OJ.noop;
        }
        return OJ.console.register(method, function() {
          var params;
          params = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
          return console[method].apply(console, params);
        });
      })();
    }
  })((typeof global !== 'undefined' && global ? global : (typeof window !== 'undefined' ? window : this)).OJ);

}).call(this);

//# sourceMappingURL=console.js.map