// Generated by CoffeeScript 1.7.1
(function() {
  (function(OJ) {
    var defer;
    defer = function(method, waitMs) {
      if (setTimeout) {
        return setTimeout(method, waitMs);
      }
    };
    OJ.register('defer', defer);
  })((typeof global !== 'undefined' && global ? global : (typeof window !== 'undefined' ? window : this)).OJ);

}).call(this);

//# sourceMappingURL=defer.js.map