// Generated by CoffeeScript 1.7.1
(function() {
  (function(OJ) {

    /*
    True if the object is a true Object or Array
     */
    var canEach, each;
    canEach = function(obj) {
      return OJ.is.plainObject(obj || OJ.is.array(obj));
    };

    /*
    Iterate an object with optional callBack and recursion
     */
    each = function(obj, onEach, recursive) {
      if (canEach(obj)) {
        _.forOwn(obj, function(val, key) {
          var quit;
          if (onEach && (val || key)) {
            quit = onEach(val, key);
            if (false === quit) {
              return false;
            }
          }
          if (true === recursive) {
            each(val, onEach, true);
          }
        });
      }
    };
    OJ.register('each', each);
  })((typeof global !== 'undefined' && global ? global : (typeof window !== 'undefined' ? window : this)).OJ);

}).call(this);

//# sourceMappingURL=each.js.map