// Generated by CoffeeScript 1.7.1
(function() {
  (function(OJ) {
    var friendlyName;
    friendlyName = 'noty';
    OJ.notifications.register(friendlyName, function(options, owner) {
      var defaults, ret;
      defaults = {
        layout: 'topRight',
        theme: 'defaultTheme',
        type: 'alert',
        text: '',
        dismissQueue: true,
        template: '<div class="noty_message"><span class="noty_text"></span><div class="noty_close"></div></div>',
        animation: {
          open: {
            height: 'toggle'
          },
          close: {
            height: 'toggle'
          },
          easing: 'swing',
          speed: 500
        },
        timeout: 5000,
        force: false,
        modal: false,
        maxVisible: 5,
        killer: false,
        closeWith: ['click'],
        callback: {
          onShow: OJ.noop,
          afterShow: OJ.noop,
          onClose: OJ.noop,
          afterClose: OJ.noop
        },
        buttons: false
      };
      OJ.extend(defaults, options, true);
      ret = noty(defaults);
      return ret;
    });
  })((typeof global !== 'undefined' && global ? global : (typeof window !== 'undefined' ? window : this)).OJ);

}).call(this);

//# sourceMappingURL=noty.js.map