// Generated by CoffeeScript 1.7.1
(function() {
  (function(OJ) {
    var rangeToSubRanges;
    rangeToSubRanges = function(n, range) {
      var chunkVal, distance, i, jump, rangeHigh, rangeLow, subRangeSize, subRanges;
      if (n == null) {
        n = 6;
      }
      if (range == null) {
        range = [];
      }
      rangeLow = _.min(range);
      rangeHigh = _.max(range);
      distance = rangeHigh - rangeLow;
      subRangeSize = distance / n;
      subRanges = {};
      chunkVal = rangeLow;
      i = 0;
      while (i < n) {
        i += 1;
        if (i < 6) {
          jump = Math.round(subRangeSize);
        } else {
          jump = Math.floor(subRangeSize);
        }
        subRanges[i] = _.range(chunkVal, chunkVal + jump);
        chunkVal += jump;
      }
      return subRanges;
    };
    OJ.register('rangeToSubRanges', rangeToSubRanges);
  })((typeof global !== 'undefined' && global ? global : (typeof window !== 'undefined' ? window : this)).OJ);

}).call(this);

//# sourceMappingURL=ranges.js.map