// Generated by CoffeeScript 1.7.1
(function() {
  (function(OJ) {
    window.initQb = function() {
      OJ.actions.querybuilder.initQbUI("qbwindow");
      OJ.structureSets.structureSet({
        name: "qbwindow",
        scope: "sql"
      });
    };
  })((typeof global !== "undefined" && global ? global : (typeof window !== "undefined" ? window : this)).OJ);

}).call(this);

//# sourceMappingURL=sqlBuilderInit.map
