// Generated by CoffeeScript 1.7.1
(function() {
  var _checkColumnIIFE;

  (_checkColumnIIFE = function(OJ) {

    /*
    Internal check column class
    @param text {String} Name of the column
     */
    var CheckColumn, checkColumn;
    CheckColumn = function(text) {
      "use strict";
      var that;
      that = OJ.grids.columns.column({
        xtype: OJ.grids.constants.xtypes.checkcolumn,
        flex: 0.075,
        text: text
      });
      that.align = "center";
      return that;
    };
    OJ.instanceOf.register("CheckColumn", CheckColumn);

    /*
    Create a check column
    @param sortable {Boolean} [sortable=true] Is Column Sortable
    @param text {String} Column Name
    @param menuDisabled {Boolean} [menuDisabled=false] Is Menu Disabled
     */
    OJ.grids.columns.register("checkColumn", checkColumn = function(sortable, text, menuDisabled) {
      "use strict";
      var ret;
      if (arguments_.length === 0) {
        throw new Error("Cannot create a column without parameters");
      }
      ret = new CheckColumn(text);
      ret.menuDisabled = menuDisabled;
      ret.sortable = sortable;
      return ret;
    });
  })((typeof global !== "undefined" && global ? global : (typeof window !== "undefined" ? window : this)).OJ);

}).call(this);

//# sourceMappingURL=checkColumn.map
