// Generated by CoffeeScript 1.7.1
(function() {
  var _columnsIIFE;

  (_columnsIIFE = function(OJ) {

    /*
    Defines a collection of columns
     */
    var Columns, columns;
    Columns = function() {
      "use strict";
      var add, that;
      that = this;
      OJ.property(that, "value", []);

      /*
      Add a column to the collection
       */
      OJ.property(that, "add", add = function(column) {
        if (!(column instanceof OJ.instanceOf.Column)) {
          throw new Error("Only columns can be added to the Columns collection");
        }
        that.value.push(column);
        return that;
      });
      return that;
    };
    OJ.instanceOf.register("Columns", Columns);

    /*
    A mechanism for generating columns
     */
    OJ.grids.columns.register("columns", columns = function() {
      "use strict";
      var ret;
      ret = new Columns();
      return ret;
    });
  })((typeof global !== "undefined" && global ? global : (typeof window !== "undefined" ? window : this)).OJ);

}).call(this);

//# sourceMappingURL=columns.map
