// Generated by CoffeeScript 1.7.1
(function() {
  var _gridColumnIIFE;

  (_gridColumnIIFE = function(OJ) {

    /*
    Private grid column class constructor
    @param text {String} Column Name
    @param editor {String} If column is editable, the type of editor
    @param flex {Number} [flex=0.125] Relative width of the column
     */
    var GridColumn, gridColumn;
    GridColumn = function(text, editor, flex) {
      "use strict";
      var that;
      that = OJ.grids.columns.column({
        xtype: OJ.grids.constants.xtypes.gridcolumn,
        flex: flex || 0.125,
        editor: editor,
        text: text
      });
      return that;
    };
    OJ.instanceOf.register("GridColumn", GridColumn);

    /*
    Create a grid column
    @param sortable {Boolean} [sortable=true] Is Column Sortable
    @param text {String} Column Name
    @param menuDisabled {Boolean} [menuDisabled=false] Is Menu Disabled
    @param flex {Number} [flex=0.125] Relative width of the column
    @param editor {String} If column is editable, the type of editor
     */
    OJ.grids.columns.register("gridColumn", gridColumn = function(sortable, text, menuDisabled, flex, editor) {
      "use strict";
      var ret;
      if (arguments_.length === 0) {
        throw new Error("Cannot create a column without parameters");
      }
      ret = new GridColumn(text, editor, flex);
      ret.menuDisabled = menuDisabled;
      ret.sortable = sortable;
      return ret;
    });
  })((typeof global !== "undefined" && global ? global : (typeof window !== "undefined" ? window : this)).OJ);

}).call(this);

//# sourceMappingURL=gridColumn.map
