// Generated by CoffeeScript 1.7.1
(function() {
  (function(OJ) {
    OJ.register("delimitedString", function(string, opts) {
      var nsInternal, nsRet;
      nsInternal = {
        newLineToDelimiter: true,
        spaceToDelimiter: true,
        removeDuplicates: true,
        delimiter: ",",
        initString: OJ.to.string(string)
      };
      nsRet = {
        array: [],
        delimited: function() {
          return nsRet.array.join(nsInternal.delimiter);
        },
        string: function(delimiter) {
          var ret;
          delimiter = delimiter || nsInternal.delimiter;
          ret = "";
          OJ.each(nsRet.array, function(val) {
            if (ret.length > 0) {
              ret += delimiter;
            }
            ret += val;
          });
          return ret;
        },
        toString: function() {
          return nsRet.string();
        },
        add: function(str) {
          nsRet.array.push(nsInternal.parse(str));
          nsInternal.deleteDuplicates();
          return nsRet;
        },
        remove: function(str) {
          var remove;
          remove = function(array) {
            return array.filter(function(item) {
              if (item !== str) {
                return true;
              }
            });
          };
          nsRet.array = remove(nsRet.array);
          return nsRet;
        },
        count: function() {
          return nsRet.array.length;
        },
        contains: function(str, caseSensitive) {
          var isCaseSensitive, match;
          isCaseSensitive = OJ.to.bool(caseSensitive);
          str = OJ.to.string(str).trim();
          if (false === isCaseSensitive) {
            str = str.toLowerCase();
          }
          match = nsRet.array.filter(function(matStr) {
            return (isCaseSensitive && OJ.to.string(matStr).trim() === str) || OJ.to.string(matStr).trim().toLowerCase() === str;
          });
          return match.length > 0;
        },
        each: function(callBack) {
          return nsRet.array.forEach(callBack);
        }
      };
      nsInternal.parse = function(str) {
        var ret;
        ret = OJ.to.string(str);
        if (nsInternal.newLineToDelimiter) {
          while (ret.indexOf("\n") !== -1) {
            ret = ret.replace(/\n/g, nsInternal.delimiter);
          }
        }
        if (nsInternal.spaceToDelimiter) {
          while (ret.indexOf(" ") !== -1) {
            ret = ret.replace(RegExp(" ", "g"), nsInternal.delimiter);
          }
        }
        while (ret.indexOf(",,") !== -1) {
          ret = ret.replace(/,,/g, nsInternal.delimiter);
        }
        return ret;
      };
      nsInternal.deleteDuplicates = function() {
        if (nsInternal.removeDuplicates) {
          (function() {
            var unique;
            unique = function(array) {
              var seen;
              seen = new Set();
              return array.filter(function(item) {
                if (false === seen.has(item)) {
                  seen.add(item);
                  return true;
                }
              });
            };
            nsRet.array = unique(nsRet.array);
          })();
        }
      };
      (function(a) {
        var delimitedString;
        if (a.length > 1 && false === OJ.is.plainObject(opts)) {
          OJ.each(a, function(val) {
            if (false === OJ.is.nullOrEmpty(val)) {
              nsRet.array.push(val);
            }
          });
        } else if (string && string.length > 0) {
          OJ.extend(nsInternal, opts);
          delimitedString = nsInternal.parse(string);
          nsInternal.initString = delimitedString;
          nsRet.array = delimitedString.split(nsInternal.delimiter);
        }
        nsInternal.deleteDuplicates();
      })(arguments);
      return nsRet;
    });
  })((typeof global !== 'undefined' && global ? global : typeof window !== 'undefined' ? window : this).OJ);

}).call(this);

//# sourceMappingURL=string.js.map