// Generated by CoffeeScript 1.7.1
(function() {
  var _treelIIFE;

  (_treelIIFE = function(OJ) {

    /*
    Create a window (sheet) object.
    @param setDef.name {String} The ClassName of the structure set to associate with ExtJS
    @param setDef.scope {String} Classname subscope
    @param setDef.autoCreateViewport {Boolean} [autoCreateViewport=false]
    @param setDef.onInit {Function} [onInit] Optional callback to be applied on construction
     */
    var ssetfunc;
    OJ.structureSets.register("structureSet", ssetfunc = function(setDef) {
      "use strict";
      return OJ.structureSets._structureSet(setDef);
    });
  })((typeof global !== "undefined" && global ? global : (typeof window !== "undefined" ? window : this)).OJ);

}).call(this);

//# sourceMappingURL=structureSet.map
