// Generated by CoffeeScript 1.7.1
(function() {
  (function() {
    'use strict';
    var createIndex, createIndexImpl;
    createIndexImpl = function(dbManager, tableName, columnName, indexName, isUnique) {
      var table;
      table = dbManager.tables[tableName];
      return table.createIndex(columnName, indexName || columnName + "Idx", {
        unique: true === isUnique
      });
    };
    createIndex = function(dbManager, tableName, columnName, indexName, isUnique) {
      var deferred;
      deferred = Q.defer();
      dbManager.schemaScripts.push(function() {
        var e, index;
        try {
          index = createIndexImpl(dbManager, tableName, columnName, indexName, isUnique);
          deferred.resolve(index);
        } catch (_error) {
          e = _error;
          console.log(e, e.stack);
          deferred.reject(new Error("Could not create a new index", e));
        }
        return dbManager.tables[tableName];
      });
      return deferred.promise;
    };
    OJ.db.index.register("create", createIndex);
  })();

}).call(this);

//# sourceMappingURL=dbIndex.map
