// Generated by CoffeeScript 1.7.1
(function() {
  (function(OJ) {
    'use strict';
    var createIndex, createIndexImpl;
    OJ.db.makeSubNameSpace('index');
    createIndexImpl = function(dbManager, tableName, columnName, indexName, isUnique) {
      var table;
      table = dbManager.tables[tableName];
      return table.createIndex(columnName, indexName || columnName + 'Idx', {
        unique: true === isUnique
      });
    };
    createIndex = function(dbManager, tableName, columnName, indexName, isUnique) {
      var deferred;
      deferred = Q.defer();
      dbManager.schemaScripts.push(function() {
        var e, index;
        try {
          index = createIndexImpl(dbManager, tableName, columnName, indexName, isUnique);
          deferred.resolve(index);
        } catch (_error) {
          e = _error;
          console.log(e, e.stack);
          deferred.reject(new Error('Could not create a new index', e));
        }
        return dbManager.tables[tableName];
      });
      return deferred.promise;
    };
    OJ.db.index.register('create', createIndex);
  })((typeof global !== 'undefined' && global ? global : (typeof window !== 'undefined' ? window : this)).OJ);

}).call(this);

//# sourceMappingURL=dbIndex.js.map