// Generated by CoffeeScript 1.7.1
(function() {
  (function() {
    'use strict';
    OJ.register("getDateFromDnJson", function(dnDate) {
      var arr, dnDateStr, localOffset, offset, ret, ticks;
      dnDateStr = OJ.to.string(dnDate);
      ret = void 0;
      ticks = void 0;
      offset = void 0;
      localOffset = void 0;
      arr = void 0;
      ret = OJ.dateTimeMinValue;
      if (false === OJ.is.nullOrEmpty(dnDateStr)) {
        dnDateStr = dnDateStr.replace("/", "");
        dnDateStr = dnDateStr.replace("Date", "");
        dnDateStr = dnDateStr.replace("(", "");
        dnDateStr = dnDateStr.replace(")", "");
        arr = dnDateStr.split("-");
        if (arr.length > 1) {
          ticks = OJ.to.number(arr[0]);
          offset = OJ.to.number(arr[1]);
          localOffset = new Date().getTimezoneOffset();
          ret = new Date(ticks - ((localOffset + (offset / 100 * 60)) * 1000));
        } else if (arr.length === 1) {
          ticks = OJ.to.number(arr[0]);
          ret = new Date(ticks);
        }
      }
      return ret;
    });
  })();

}).call(this);

//# sourceMappingURL=date.js.map