// Generated by CoffeeScript 1.7.1
(function() {
  (function(OJ) {

    /*
    Add a property to an object
     */
    var property;
    property = function(obj, name, value, writable, configurable, enumerable) {
      if (!obj) {
        throw new Error("Cannot define a property without an Object.");
      }
      if (!name) {
        throw new Error("Cannot create a property without a valid property name.");
      }
      obj[name] = value;
      return obj;
    };
    OJ.register("property", property);
  })((typeof global !== 'undefined' && global ? global : (typeof window !== 'undefined' ? window : this)).OJ);

}).call(this);

//# sourceMappingURL=property.js.map