// Generated by CoffeeScript 1.7.1
(function() {
  (function(OJ) {
    var initQbUI;
    initQbUI = function(qbId) {
      var items, onInit, sheet;
      Ext.tip.QuickTipManager.init();
      Ext.namespace(OJ.name + ".sql");
      onInit = function(that) {
        OJ.actions.sql.init();
        window.SyntaxHighlighter.defaults["gutter"] = false;
        window.SyntaxHighlighter.defaults["toolbar"] = false;
        that.dockedItems = [
          {
            xtype: "toolbar",
            dock: "top",
            items: [
              {
                xtype: "tbfill"
              }, {
                text: "Save",
                icon: "img/icon-save.gif"
              }, {
                text: "Run",
                icon: "img/run.png"
              }
            ]
          }
        ];
      };
      sheet = OJ.sheets.sheet({
        id: qbId,
        onInit: onInit
      });
      sheet.addProp("height", 620);
      sheet.addProp("width", 1000);
      sheet.addProp("title", "Visual SQL Query Builder");
      sheet.addProp("layout", {
        type: "border"
      });
      items = [
        OJ.actions.querybuilder.qbOutputPanel({}), {
          xtype: "panel",
          border: false,
          height: 400,
          margin: 5,
          layout: {
            type: "border"
          },
          region: "north",
          split: true,
          items: [OJ.actions.querybuilder.qbTablePanel({}), OJ.actions.querybuilder.qbFineTuningGrid({}), OJ.actions.querybuilder.qbTablesTree({})]
        }
      ];
      sheet.addProp("items", items);
      sheet.init();
    };
    OJ.actions.querybuilder.register("initQbUI", initQbUI);
  })((typeof global !== "undefined" && global ? global : (typeof window !== "undefined" ? window : this)).OJ);

}).call(this);

//# sourceMappingURL=_initQbUI.map
