// Generated by CoffeeScript 1.7.1
(function() {
  (function(OJ) {
    var initOutputPanel;
    initOutputPanel = function(panelDef) {
      var panel;
      panel = OJ.panels.panel({
        name: "Ext." + OJ.name + ".qbOutputPanel",
        alias: ["widget.qbOutputPanel"],
        id: "qbOutputPanel"
      });
      panel.subscribers.add(OJ.panels.constants.subscribers.afterlayout, function() {
        window.SyntaxHighlighter.highlight();
      });
      panel.init();
      return {
        xtype: "qbOutputPanel",
        border: false,
        region: "center",
        autoScroll: true,
        html: "<pre class=\"brush: sql\">SQL Output Window</pre>",
        margin: 5,
        height: 150,
        split: true
      };
    };
    OJ.actions.querybuilder.register("qbOutputPanel", initOutputPanel);
  })((typeof global !== "undefined" && global ? global : (typeof window !== "undefined" ? window : this)).OJ);

}).call(this);

//# sourceMappingURL=qbOutputPanel.map
