// Generated by CoffeeScript 1.7.1
(function() {
  (function(OJ) {
    var initTableTree;
    initTableTree = function(tabTreeDef) {
      var getRandomTableTreeNodes, initTreeDragZone, tree;
      initTreeDragZone = function(thisTree, t) {
        thisTree.view.dragZone = new Ext.tree.ViewDragZone({
          view: thisTree.view,
          ddGroup: "sqlDDGroup",
          dragText: "{0} Selected Table{1}",
          repairHighlightColor: "c3daf9",
          repairHighlight: Ext.enableFx
        });
      };
      getRandomTableTreeNodes = function() {
        var i, ret, tableName;
        ret = [];
        i = 0;
        while (i < 15) {
          tableName = Faker.random.catch_phrase_noun().replace(" ", "_").replace("-", "_");
          ret.push(OJ.trees.treeNode({
            text: tableName
          }));
          i += 1;
        }
        return ret;
      };

      /*
      Define the tree
       */
      tree = OJ.trees.tree({
        id: "qbTablesTree",
        store: OJ.trees.treeStore({
          rootText: "Database Tables",
          children: getRandomTableTreeNodes()
        })
      });

      /*
      Add the subscribers
       */
      tree.subscribers.add(OJ.trees.constants.subscribers.afterrender, function(extView, eOpts) {
        var that;
        that = extView;
        initTreeDragZone(that, tree);
      });
      tree.subscribers.add(OJ.trees.constants.subscribers.itemdblclick, function(extView, record, item, index, e, eOpts) {
        var qbTablePanel;
        qbTablePanel = void 0;
        qbTablePanel = Ext.getCmp("qbTablePanel");
        qbTablePanel.add({
          xtype: "qbSqlWindowTable",
          constrain: true,
          title: record.get("text")
        }).show();
      });
      tree.init();
      return {
        xtype: "qbTablesTree",
        border: false,
        region: "west",
        width: 200,
        height: 400,
        split: true
      };
    };
    OJ.actions.querybuilder.register("qbTablesTree", initTableTree);
  })((typeof global !== "undefined" && global ? global : (typeof window !== "undefined" ? window : this)).OJ);

}).call(this);

//# sourceMappingURL=qbTablesTree.map
