// Generated by CoffeeScript 1.7.1

/*
The Tabble Join Store represents the join data bound between columns across tables
 */

(function() {
  var _joinsStoreIIFE;

  (_joinsStoreIIFE = function(OJ) {

    /*
    Instance a collection of fields to describe a JOIN in the SQL output table
     */
    var SqlDragDropTableJoinModel, SqlDragDropTableJoinStore;
    SqlDragDropTableJoinModel = OJ.dataModels.dataModel({
      name: "Ext." + OJ.name + ".SqlDragDropTableJoinModel",
      dataTypeCollection: [["id"], ["leftTableId"], ["rightTableId"], ["leftTableField"], ["rightTableField"], ["joinCondition"], ["joinType", "boolean"]]
    });
    OJ.actions.querybuilder.register("SqlDragDropTableJoinModel", SqlDragDropTableJoinModel);

    /*
    Define the store
     */
    SqlDragDropTableJoinStore = OJ.stores.store({
      name: "Ext." + OJ.name + ".SqlDragDropTableJoinStore",
      dataModel: OJ.actions.querybuilder.SqlDragDropTableJoinModel
    });

    /*
    Put the class into the namespace
     */
    OJ.actions.querybuilder.register("SqlDragDropTableJoinStore", SqlDragDropTableJoinStore);
  })((typeof global !== "undefined" && global ? global : (typeof window !== "undefined" ? window : this)).OJ);

}).call(this);

//# sourceMappingURL=SqlDragDropTableJoinStore.map
