// Generated by CoffeeScript 1.7.1

/*
The Table Store represents the data bound to a Database Table
 */

(function() {
  var _joinsStoreIIFE;

  (_joinsStoreIIFE = function(OJ) {

    /*
    Instance a data type collection to describe a table in the table Tree
     */
    var SqlTableNameModel, SqlTableNameStore;
    SqlTableNameModel = OJ.dataModels.dataModel({
      name: "Ext." + OJ.name + ".SqlTableNameModel",
      dataTypeCollection: [["id"], ["tableName"], ["tableAlias"]]
    });
    OJ.actions.querybuilder.register("SqlTableNameModel", SqlTableNameModel);

    /*
    Define the store
     */
    SqlTableNameStore = OJ.stores.store({
      name: "Ext." + OJ.name + ".SqlTableNameStore",
      dataModel: OJ.actions.querybuilder.SqlTableNameModel
    });

    /*
    Put the class into the namespace
     */
    OJ.actions.querybuilder.register("SqlTableNameStore", SqlTableNameStore);
  })((typeof global !== "undefined" && global ? global : (typeof window !== "undefined" ? window : this)).OJ);

}).call(this);

//# sourceMappingURL=SqlTableNameStore.map
