// Generated by CoffeeScript 1.7.1
(function() {
  (function(OJ) {
    var onDrag, sprite, spriteDef, startDrag;
    startDrag = function(id) {
      var me, qbTablePanel, win, xyChildPos, xyParentPos;
      me = this;
      win = void 0;
      qbTablePanel = void 0;
      xyParentPos = void 0;
      xyChildPos = void 0;
      win = Ext.getCmp(id);
      qbTablePanel = Ext.getCmp("qbTablePanel");
      xyParentPos = qbTablePanel.el.getXY();
      xyChildPos = win.el.getXY();
      me.prev = me.surface.transformToViewBox(xyChildPos[0] - xyParentPos[0] + 2, xyChildPos[1] - xyParentPos[1] + 2);
    };
    onDrag = function(relPosMovement) {
      var me, newX, newY;
      me = this;
      newX = void 0;
      newY = void 0;
      newX = me.prev[0] + relPosMovement[0];
      newY = me.prev[1] + relPosMovement[1];
      me.setAttributes({
        x: newX,
        y: newY
      }, true);
    };
    spriteDef = OJ.classDefinition({
      name: "Ext." + OJ.name + ".SqlTableJoinSprite",
      extend: "Ext.draw.Sprite",
      alias: ["widget.SqlTableJoinSprite"],
      onDefine: function(classDef) {
        OJ.property(classDef, "bConnections", false);
        OJ.property(classDef, "startDrag", startDrag);
        OJ.property(classDef, "onDrag", onDrag);
      }
    });
    sprite = spriteDef.init();
    OJ.actions.querybuilder.register("SqlTableJoinSprite", sprite);
  })((typeof global !== "undefined" && global ? global : (typeof window !== "undefined" ? window : this)).OJ);

}).call(this);

//# sourceMappingURL=SqlTableJoinSprite.map
