// Generated by CoffeeScript 1.7.1
(function() {
  var _Error;

  (_Error = function(OJ) {
    var AssignmentError, ClassInheritanceError, _AE, _CIE;
    AssignmentError = OJ.Class("AssignmentError", Error, _AE = function(message, fileName, lineNumber, exception) {
      'use strict';
      var error;
      error = this;
      error.name = "AssignmentError";
      error.message = message || "Default Message";
      if (fileName) {
        error.fileName = fileName;
      }
      if (lineNumber) {
        error.lineNumber = lineNumber;
      }
      OJ.console.error(error, {
        outerStack: exception.stack,
        outerMessage: exception.message
      });
      return error;
    });
    OJ.errors.register("AssignmentError", function(message, fileName, lineNumber, exception) {
      return new AssignmentError(message, fileName, lineNumber, exception);
    });
    ClassInheritanceError = OJ.Class("ClassInheritanceError", Error, _CIE = function(message, fileName, lineNumber, exception) {
      'use strict';
      var error;
      error = this;
      error.name = "ClassInheritanceError";
      error.message = message || "Default Message";
      if (fileName) {
        error.fileName = fileName;
      }
      if (lineNumber) {
        error.lineNumber = lineNumber;
      }
      OJ.console.error(error, {
        outerStack: exception.stack,
        outerMessage: exception.message
      });
      return error;
    });
    OJ.errors.register("ClassInheritanceError", function(message, fileName, lineNumber, exception) {
      'use strict';
      return new ClassInheritanceError(message, fileName, lineNumber, exception);
    });
  })((typeof global !== 'undefined' && global ? global : (typeof window !== 'undefined' ? window : this)).OJ);

}).call(this);

//# sourceMappingURL=errors.map
