// Generated by CoffeeScript 1.7.1
(function() {
  (function(OJ) {
    var subNameSpaces;
    subNameSpaces = ['errors', 'enums', 'is', 'instanceOf', 'to', 'nodes', 'db', 'components', 'controls', 'inputs', 'notifications', 'history', 'cookie', 'async'];
    _.each(subNameSpaces, function(name) {
      return OJ.makeSubNameSpace(name);
    });

    /*
    Configuration variables
     */
    OJ['GENERATE_UNIQUE_IDS'] = false;
    OJ['DEFAULT_COMPONENT_ROOT_NODETYPE'] = 'div';
    OJ['TRACK_ON_ERROR'] = false;
  })((typeof global !== 'undefined' && global ? global : typeof window !== 'undefined' ? window : this).OJ);

}).call(this);

//# sourceMappingURL=ojInit.js.map