// Generated by CoffeeScript 1.7.1
(function() {
  (function(OJ) {
    OJ.makeSubNameSpace('errors');
    OJ.makeSubNameSpace('enums');
    OJ.makeSubNameSpace('is');
    OJ.makeSubNameSpace('instanceOf');
    OJ.makeSubNameSpace('to');
    OJ.makeSubNameSpace('nodes');
    OJ.makeSubNameSpace('db');
    OJ.makeSubNameSpace('components');
    OJ.components.register('members', {});
    OJ['GENERATE_UNIQUE_IDS'] = false;
  })((typeof global !== 'undefined' && global ? global : typeof window !== 'undefined' ? window : this).OJ);

}).call(this);

//# sourceMappingURL=ojInit.map
