// Generated by CoffeeScript 1.7.1
(function() {
  (function(OJ) {
    var optionsProto;
    optionsProto = function() {
      OJ.property(this, "accesskey", null, false, true);
      OJ.property(this, "class", null, false, true);
      OJ.property(this, "contenteditable", null, false, true);
      OJ.property(this, "contextmenu", null, false, true);
      OJ.property(this, "draggable", null, false, true);
      OJ.property(this, "dropzone", null, false, true);
      OJ.property(this, "hidden", null, false, true);
      OJ.property(this, "spellcheck", null, false, true);
      OJ.property(this, "style", null, false, true);
      OJ.property(this, "tabindex", null, false, true);
      OJ.property(this, "title", null, false, true);
      return this;
    };
    OJ.node.register("globalAttributes", function(options) {
      var globOpts, ret;
      globOpts = OJ.object(optionsProto.prototype);
      ret = globOpts;
      if (OJ.is.plainObject(options)) {
        OJ.property(options, "globalAttributes", globOpts);
        ret = options;
      }
      return ret;
    });
  })((typeof global !== 'undefined' && global ? global : (typeof window !== 'undefined' ? window : this)).OJ, (typeof global !== 'undefined' && global ? global : (typeof window !== 'undefined' ? window : this)).OJ["?"]);

}).call(this);

//# sourceMappingURL=domNodeAttributes.map
