// Generated by CoffeeScript 1.7.1
(function() {
  (function(OJ) {
    var assert, console, count, length, method, methods, noop, thisGlobal;
    method = void 0;
    noop = _.noop;
    methods = ["assert", "clear", "count", "debug", "dir", "dirxml", "error", "exception", "group", "groupCollapsed", "groupEnd", "info", "log", "markTimeline", "profile", "profileEnd", "table", "time", "timeEnd", "timeStamp", "trace", "warn"];
    length = methods.length;
    thisGlobal = (typeof global !== 'undefined' && global ? global : typeof window !== 'undefined' ? window : this);
    console = (thisGlobal.console = thisGlobal.console || {});
    while (length--) {
      method = methods[length];
      if (!console[method]) {
        console[method] = noop;
      }
    }
    OJ.makeSubNameSpace("console");
    OJ.console.register("assert", assert = function(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p) {
      'use strict';
      console.assert(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p);
    });
    OJ.console.register("count", count = function(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p) {
      'use strict';
      console.count(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p);
    });
    OJ.console.register("error", function(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p) {
      'use strict';
      console.error(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p);
    });
    OJ.console.register("group", function(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p) {
      'use strict';
      console.group(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p);
    });
    OJ.console.register("groupCollapsed", function(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p) {
      'use strict';
      console.groupCollapsed(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p);
    });
    OJ.console.register("groupEnd", function(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p) {
      'use strict';
      console.groupEnd(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p);
    });
    OJ.console.register("info", function(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p) {
      'use strict';
      console.info(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p);
    });
    OJ.console.register("log", function(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p) {
      'use strict';
      console.log(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p);
    });
    OJ.console.register("profile", function(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p) {
      'use strict';
      console.profile(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p);
    });
    OJ.console.register("profileEnd", function(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p) {
      'use strict';
      console.profileEnd(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p);
    });
    OJ.console.register("table", function(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p) {
      'use strict';
      console.table(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p);
    });
    OJ.console.register("time", function(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p) {
      'use strict';
      console.time(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p);
    });
    OJ.console.register("timeEnd", function(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p) {
      'use strict';
      console.timeEnd(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p);
    });
    OJ.console.register("trace", function(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p) {
      'use strict';
      console.trace(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p);
    });
    OJ.console.register("warn", function(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p) {
      'use strict';
      console.warn(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p);
    });
  })((typeof global !== 'undefined' && global ? global : typeof window !== 'undefined' ? window : this).OJ);

}).call(this);

//# sourceMappingURL=console.map
