// Generated by CoffeeScript 1.7.1
(function() {
  (function(OJ) {
    var onError;
    if (OJ.TRACK_ON_ERROR) {
      onError = OJ.global.onerror;

      /*
      Log errors to the console
       */
      OJ.global.onerror = function(msg, url, lineNumber) {
        var ret;
        ret = false;
        OJ.console.warn("%s\r url: %s\r line: %d", msg, url, lineNumber);
        if (onError) {
          ret = onError(msg, url, lineNumber);
        }
        return ret;
      };
    }
  })((typeof global !== 'undefined' && global ? global : (typeof window !== 'undefined' ? window : this)).OJ);

}).call(this);

//# sourceMappingURL=error.js.map