// Generated by CoffeeScript 1.7.1
(function() {
  (function(OJ) {
    var onError, thisGlobal;
    thisGlobal = (typeof global !== 'undefined' && global ? global : (typeof window !== 'undefined' ? window : this));
    onError = thisGlobal.onerror;

    /*
    Log errors to the console
     */
    thisGlobal.onerror = function(msg, url, lineNumber) {
      console.warn("%s\r url: %s\r line: %d", msg, url, lineNumber);
      if (onError) {
        onError(arguments);
      }
      return false;
    };
  })((typeof global !== 'undefined' && global ? global : (typeof window !== 'undefined' ? window : this)).OJ);

}).call(this);

//# sourceMappingURL=error.map
