// Generated by CoffeeScript 1.7.1
(function() {
  (function(OJ) {

    /*
    Create an instance of Object
    @param properties {Object} [properties={}] properties to define on the Object
    @param inheritsFromPrototype {Prototype} [inheritsFromPrototype=null] The prototype to inherit from
     */
    var object;
    object = function(properties, inheritsFromPrototype) {
      var obj;
      if (!inheritsFromPrototype) {
        inheritsFromPrototype = null;
      }
      if (!properties) {
        properties = {};
      }
      obj = Object.create(inheritsFromPrototype, properties);

      /*
      Add a property to the object and return it
       */
      OJ.property(obj, "add", (function(name, val, writable, configurable, enumerable) {
        return OJ.property(obj, name, val, writable, configurable, enumerable);
      }), false, false, false);
      return obj;
    };
    OJ.register("object", object);
  })((typeof global !== 'undefined' && global ? global : typeof window !== 'undefined' ? window : this).OJ);

}).call(this);

//# sourceMappingURL=object.map
