// Generated by CoffeeScript 1.7.1
(function() {
  (function(OJ) {
    var inheritsFrom, onError, thisGlobal;
    thisGlobal = (typeof global !== 'undefined' && global ? global : (typeof thisGlobal !== 'undefined' ? thisGlobal : this));
    onError = thisGlobal.onerror;

    /*
    Log errors to the console
     */
    thisGlobal.onerror = function(msg, url, lineNumber) {
      console.warn("%s\rurl: %s\rline: %d", msg, url, lineNumber);
      if (onError) {
        onError(arguments_);
      }
      return false;
    };
    if (!thisGlobal.setImmediate) {

      /*
      Shim for setImmediate
       */
      thisGlobal.setImmediate = function(func, args) {
        return thisGlobal.setTimeout(func, 0, args);
      };
      thisGlobal.clearImmediate = thisGlobal.clearTimeout;
    }
    if (!Function.prototype.inheritsFrom) {
      Object.defineProperties(Function.prototype, {
        inheritsFrom: {

          /*
          Easy inheritance by prototype
           */
          value: inheritsFrom = function(parentClassOrObject) {
            if (parentClassOrObject.constructor === Function) {
              this.prototype = new parentClassOrObject;
              this.prototype.constructor = this;
              this.prototype.parent = parentClassOrObject.prototype;
            } else {
              this.prototype = parentClassOrObject;
              this.prototype.constructor = this;
              this.prototype.parent = parentClassOrObject;
            }
            return this;
          }
        }
      });
    }
  })((typeof global !== 'undefined' && global ? global : (typeof window !== 'undefined' ? window : this)).OJ);

}).call(this);

//# sourceMappingURL=shims.map
