// Generated by CoffeeScript 1.7.1
(function() {
  (function(OJ) {

    /*
    Generates a random string that complies to the RFC 4122 specification for GUID/UUID.
    (e.g. 'B42A153F-1D9A-4F92-9903-92C11DD684D2')
    While not a true UUID, for the purposes of this application, it should be sufficient.
     */
    var createFauxUUID;
    createFauxUUID = function() {
      var hexDigits, i, s, uuid;
      s = [];
      s.length = 36;
      hexDigits = "0123456789abcdef";
      i = 0;
      while (i < 36) {
        s[i] = hexDigits.substr(Math.floor(Math.random() * 0x10), 1);
        i += 1;
      }
      s[14] = "4";
      s[19] = hexDigits.substr((s[19] & 0x3) | 0x8, 1);
      s[8] = s[13] = s[18] = s[23] = "-";
      uuid = s.join("");
      return uuid;
    };
    OJ.register("createUUID", createFauxUUID);
  })((typeof global !== 'undefined' && global ? global : (typeof window !== 'undefined' ? window : this)).OJ);

}).call(this);

//# sourceMappingURL=uuid.js.map