// Generated by CoffeeScript 1.7.1
(function() {
  (function(OJ) {

    /*
    Elements base class. This will instance a new node from metadata, returning an object that can be consumed
     */
    var _Element;
    _Element = OJ.Class("_Element", OJ.metadata.Node, function(elementName) {
      var element;
      element = this;
      element.nodeName = elementName.toUpperCase();
      return element;
    });
    OJ.metadata.register("_Element", _Element);
    OJ.elements.register("_element", function(parentNode, elementName, options) {
      var element, html, val, vendorHtml;
      val = options.display || options.value || "";
      html = "<" + elementName + " id=\"" + options.id + "\" value=\"" + val + "\"";
      if (elementName !== "input") {
        html += "\">" + val + "</" + elementName + ">";
      } else {
        html += "/>";
      }
      vendorHtml = OJ.to.vendorDomObjFromString(html);
      element = new _Element(options.id, vendorHtml[0], vendorHtml);
      parentNode.addChild(element);
      element.addClass(options.cssclass);
      element.css(options.styles);
      element.attr(options.attr);
      element.prop(options.prop);
      element.on("change", function() {});
      Object.defineProperty(element, "nsVal", {
        get: function() {
          return options.value;
        },
        set: function(val) {
          options.value = val;
          return val;
        }
      });
      Object.defineProperty(element, "val", {
        value: function() {
          return element[0].getAttribute("value");
        }
      });
      return element;
    });
  })((typeof global !== 'undefined' && global ? global : (typeof window !== 'undefined' ? window : this)).OJ);

}).call(this);

//# sourceMappingURL=_element.map
