// Generated by CoffeeScript 1.7.1
(function() {
  (function(OJ) {
    var Div;
    Div = OJ.Class("Div", OJ.metadata.Node, function(parentNode, options) {
      var div;
      div = OJ.elements._element(parentNode, "div", options);
      return div;
    });
    OJ.metadata.register("Div", Div);
    OJ.elements.register("div", function(parentNode, options) {
      var div;
      div = new Div(parentNode, options);
      return div;
    });
  })((typeof global !== 'undefined' && global ? global : (typeof window !== 'undefined' ? window : this)).OJ);

}).call(this);

//# sourceMappingURL=div.map
