// Generated by CoffeeScript 1.7.1
(function() {
  (function(OJ) {
    var Input;
    Input = OJ.Class("Input", OJ.metadata.Node, function(NsNode, options) {
      var input;
      input = OJ.elements._element(NsNode, "input", options);
      return input;
    });
    OJ.metadata.register("Input", Input);
    OJ.elements.register("input", function(NsNode, options) {
      var input;
      input = OJ.metadata.Input(NsNode, options);
      return input;
    });
  })((typeof global !== 'undefined' && global ? global : (typeof window !== 'undefined' ? window : this)).OJ);

}).call(this);

//# sourceMappingURL=input.map
