// Generated by CoffeeScript 1.7.1
(function() {
  (function(OJ) {
    var Span;
    Span = OJ.Class("Span", OJ.metadata.Node, function() {
      var span;
      span = this;
      span.nodeName = "SPAN";
      return span;
    });
    OJ.metadata.register("Span", Span);
    OJ.elements.register("span", function(NsNode, options) {
      var html, span, vendorHtml;
      html = "<span id=\"" + options.id + "\" value=\"" + options.value + "\">" + options.display || options.value + "</span>";
      vendorHtml = OJ.to.vendorDomObjFromString(html);
      span = new OJ.metadata.Span(options.id, vendorHtml[0], vendorHtml);
      NsNode.addChild(span);
      span.addClass(options.cssclass);
      span.css(options.styles);
      span.attr(options.attr);
      span.prop(options.prop);
      Object.defineProperty(span, "nsVal", {
        get: function() {
          return options.value;
        },
        set: function(val) {
          options.value = val;
          return val;
        }
      });
      Object.defineProperty(span, "val", {
        value: function() {
          return span[0].getAttribute("value");
        }
      });
      return span;
    });
  })((typeof global !== 'undefined' && global ? global : (typeof window !== 'undefined' ? window : this)).OJ);

}).call(this);

//# sourceMappingURL=span.map
